// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ospats2_c
List ospats2_c(NumericMatrix D2, IntegerVector strat_init, NumericVector OA2_init, int niter_inner, int niter_outer, double temperature, double coolingrate, int verbose);
RcppExport SEXP _ospats2_ospats2_c(SEXP D2SEXP, SEXP strat_initSEXP, SEXP OA2_initSEXP, SEXP niter_innerSEXP, SEXP niter_outerSEXP, SEXP temperatureSEXP, SEXP coolingrateSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D2(D2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strat_init(strat_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type OA2_init(OA2_initSEXP);
    Rcpp::traits::input_parameter< int >::type niter_inner(niter_innerSEXP);
    Rcpp::traits::input_parameter< int >::type niter_outer(niter_outerSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type coolingrate(coolingrateSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(ospats2_c(D2, strat_init, OA2_init, niter_inner, niter_outer, temperature, coolingrate, verbose));
    return rcpp_result_gen;
END_RCPP
}
// ospats_ref_c
List ospats_ref_c(NumericMatrix D2, IntegerVector strat_init, NumericVector OA2_init, int niter_inner, int niter_outer, double temperature, double coolingrate, int verbose);
RcppExport SEXP _ospats2_ospats_ref_c(SEXP D2SEXP, SEXP strat_initSEXP, SEXP OA2_initSEXP, SEXP niter_innerSEXP, SEXP niter_outerSEXP, SEXP temperatureSEXP, SEXP coolingrateSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D2(D2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strat_init(strat_initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type OA2_init(OA2_initSEXP);
    Rcpp::traits::input_parameter< int >::type niter_inner(niter_innerSEXP);
    Rcpp::traits::input_parameter< int >::type niter_outer(niter_outerSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type coolingrate(coolingrateSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(ospats_ref_c(D2, strat_init, OA2_init, niter_inner, niter_outer, temperature, coolingrate, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ospats2_ospats2_c", (DL_FUNC) &_ospats2_ospats2_c, 8},
    {"_ospats2_ospats_ref_c", (DL_FUNC) &_ospats2_ospats_ref_c, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_ospats2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
