# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ospats2_c <- function(D2, strat_init, OA2_init, niter_inner, niter_outer, temperature, coolingrate, verbose) {
    .Call('_ospats2_ospats2_c', PACKAGE = 'ospats2', D2, strat_init, OA2_init, niter_inner, niter_outer, temperature, coolingrate, verbose)
}

ospats_ref_c <- function(D2, strat_init, OA2_init, niter_inner, niter_outer, temperature, coolingrate, verbose) {
    .Call('_ospats2_ospats_ref_c', PACKAGE = 'ospats2', D2, strat_init, OA2_init, niter_inner, niter_outer, temperature, coolingrate, verbose)
}

